### PR TITLE
updating regex for service name and ipv4 addresses

### PR DESCRIPTION
**Pull request by SethHollandsworth**
With one workflow my team tested we found a couple of the regexes have some gaps in expected passing strings.

1. svc_name should allow alphanumerics according to [this](https://kubernetes.io/docs/concepts/services-networking/service/#:~:text=The%20name%20of%20a%20Service%20object%20must%20be%20a%20valid%20RFC%201035%20label%20name.) and [this](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names)
2. ipv4_a is not passing for [this test case](https://regex101.com/r/jLz1JN/1) that appeared when making a service. I found another regex on stackoverflow [here](https://stackoverflow.com/questions/5284147/validating-ipv4-addresses-with-regexp) that [seems to work](https://regex101.com/r/cwTEn6/1). If there are some requirements that the new regex is not following, please let me know!

Thanks!

### CODE REVIEW

**Review by BryceDFisher — APPROVED** [review]

**Comment by SethHollandsworth** [comment]
Sorry for the force pushes, I was `commit --amend` ing to add ksayid as a coauthor

**Review by Redent0r — APPROVED** [review]

**Comment by ms-mahuber** [comment]
Please re-run genPolicy on Dan's policy test yamls and commit those for which policy annotations change

**Comment by ms-mahuber** [comment]
The PR looks good after updating the test samples. While it is ready to merge, this branch is currently in a locked state for an unrelated ongoing investigation. We will go ahead and merge it once the situation is resolved.

**Review by danmihai1 — APPROVED** [review]

**Comment by ms-mahuber** [comment]
> The PR looks good after updating the test samples. While it is ready to merge, this branch is currently in a locked state for an unrelated ongoing investigation. We will go ahead and merge it once the situation is resolved.
> 
> Please do not merge yet.

cc-msft-prototypes is functional again. PR can be merged

**Review by ms-mahuber — APPROVED** [review]

**Pull request merged**
