### PR TITLE
tools: Remove cgroupv1 kernel parameters for kata

### PR DESCRIPTION
**Pull request by miz060**
###### Merge Checklist  
- [x] Followed patch format from upstream recommendation: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
  - [x] Included a single commit in a given PR - at least unless there are related commits and each makes sense as a change on its own.
- [x] Aware about the PR to be merged using "create a merge commit" rather than "squash and merge" (or similar)
- [x] genPolicy only: Ensured the tool still builds on Windows
- [x] The `upstream/missing` label (or `upstream/not-needed`) has been set on the PR. 

###### Summary 

Remove cgroupv1 kernel parameters for kata

###### Test Methodology
Conformance test result: [585964](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=585964&view=results)

### CODE REVIEW

**Comment by ms-mahuber** [comment]
Please do not merge :) But thanks. Please take a look at the code in: https://github.com/microsoft/kata-containers/tree/mahuber/uvm-spec-build

I believe this does match your needs?

**Comment by ms-mahuber** [comment]
> Please do not merge :) But thanks. Please take a look at the code in: https://github.com/microsoft/kata-containers/tree/mahuber/uvm-spec-build
> 
> I believe this does match your needs?

I think it matches your needs but we will also want to set the following, conditionally: `DEFSANDBOXCGROUPONLY=true`

**Comment by sprt** [comment]
Why is this needed?

**Comment by miz060** [comment]
> Please do not merge :) But thanks. Please take a look at the code in: https://github.com/microsoft/kata-containers/tree/mahuber/uvm-spec-build
> 
> I believe this does match your needs?

Yep this should do. Closing PR now...

**Comment by miz060** [comment]
> Why is this needed?

This is to support cgroupv2 Mariner 3 Kata image. But this code change address the same issue:
https://github.com/microsoft/kata-containers/tree/mahuber/uvm-spec-build

I'll close this PR now.

**Pull request closed without merging**
