### PR TITLE
genpolicy: add persistent storage support for stateful sets

### PR DESCRIPTION
**Pull request by arc9693**
###### Merge Checklist  
- [x] Followed patch format from upstream recommendation: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
  - [x] Included a single commit in a given PR - at least unless there are related commits and each makes sense as a change on its own.
- [x] Aware about the PR to be merged using "create a merge commit" rather than "squash and merge" (or similar)
- [x] genPolicy only: Ensured the tool still builds on Windows
- [x] The `upstream/missing` label (or `upstream/not-needed`) has been set on the PR. 

###### Summary 

This change adds support for volume claim templates for stateful sets. This is useful for stateful sets that require persistent storage, using cc-azurefile-csi, cc-azuredisk-csi or other storage providers.

### CODE REVIEW

**Review by ms-mahuber — APPROVED** [review]
Approve pending test automation

**Comment by Redent0r** [comment]
LGTM. Run `python3 update_policy_samples.py` to fix https://github.com/microsoft/kata-containers/actions/runs/9351824061/job/25738511724?pr=199 and follow https://dev.azure.com/mariner-org/mariner/_wiki/wikis/mariner.wiki/3368/Testing-genpolicy to trigger a test run

**Comment by ms-mahuber** [comment]
[like]  Manuel Huber reacted to your message:
________________________________

**Comment by arc9693** [comment]
Tests run after samples update: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580957&view=results

**Review by danmihai1 — APPROVED** [review]

**Comment by arc9693** [comment]
Test run with latest updates: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582238&view=results 100% passed ✅

**Pull request merged**
